### ISSUE TITLE
Fix frontend

### ISSUE THREAD

**Issue by Dilschat** [OmOmTeam/Logistic-company-employees-app#5]
Чтобы увидеть валидный фронт тебе нужно будет запускать сервак. И так как я пока не смог сделать мок сервера. нужно будет еще запускать питоновский сервак на фласке от Нияза. Спросишь у него.
 эндпоинты: /login  ; /main  ; /next_order (+если ты засабмитишь ордер попадешь на новую страницу /next_order)

1. Поправить положение кнопок на всех страницах
2. Поправить форму в addOrder.html
3. добавить в main.html кнопку get order

Все что связано с линками поправлю сам. Стили уже грузятся нормально.

**Comment by ViktoriaRo** [comment]
form for addOrder is styled but I couldn't fix the problem with server
